os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: stable
      target: i686-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: i686-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
      #cargoflags: --features "unstable"
    - channel: nightly
      target: i686-pc-windows-msvc
      #cargoflags: --features "unstable"

    - channel: stable
      target: x86_64-pc-windows-gnu
      MSYS_BITS: 64
    - channel: stable
      target: i686-pc-windows-gnu
      MSYS_BITS: 32
    - channel: beta
      target: x86_64-pc-windows-gnu
      MSYS_BITS: 64
    - channel: beta
      target: i686-pc-windows-gnu
      MSYS_BITS: 32
    - channel: nightly
      target: x86_64-pc-windows-gnu
      MSYS_BITS: 64
      #cargoflags: --features "unstable"
    - channel: nightly
      target: i686-pc-windows-gnu
      MSYS_BITS: 32
      #cargoflags: --features "unstable"

matrix:
  allow_failures:
    - channel: nightly

install:
  - appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
  - rustup-init -yv --default-toolchain %channel% --default-host %target%
  - set PATH=%PATH%;%USERPROFILE%\.cargo\bin
  - if defined MSYS_BITS set PATH=C:\msys64\mingw%MSYS_BITS%\bin;C:\msys64\usr\bin;%PATH%
  - rustc -vV
  - cargo -vV

build: false

test_script:
- cargo test --verbose %cargoflags%
